//! Generates `keys.rs`: one `pub const` per leaf of the CLI bundle.
//!
//! The JSON is the type. A call site names a string as `keys::chat::NO_MODEL`,
//! and a key that is not in the bundle is a compile error rather than a label
//! rendered as its own dotted path. Plural forms collapse to one constant:
//! `files_one` and `files_other` are both `FILES`, because the lookup adds the
//! suffix from `count` and no call site should have to.
//!
//! The same file is embedded with `include_str!` at runtime, so the constants and
//! the templates can never come from two different revisions of the bundle.

use std::collections::BTreeMap;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

/// Where the bundle lives, relative to this crate.
const BUNDLE: &str = "../../packages/i18n/locales/en/cli.json";

/// The CLDR plural categories i18next appends to a key.
const PLURAL_SUFFIXES: [&str; 6] = ["zero", "one", "two", "few", "many", "other"];

/// A namespace: nested namespaces and the leaves directly under it.
#[derive(Default)]
struct Namespace {
    children: BTreeMap<String, Namespace>,
    /// Base key name → every template filed under it (one, or one per plural form).
    leaves: BTreeMap<String, Vec<(String, String)>>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let bundle_path = manifest_dir.join(BUNDLE);
    println!("cargo:rerun-if-changed={}", bundle_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let json: Value = serde_json::from_str(&fs::read_to_string(&bundle_path)?)?;
    let mut root = Namespace::default();
    let mut all = Vec::new();
    collect(&json, &[], &mut root, &mut all)?;
    all.sort();
    all.dedup();

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from {BUNDLE}; do not edit.")?;
    writeln!(
        out,
        "/// Every key the bundle defines, plural suffix stripped, sorted."
    )?;
    writeln!(out, "pub const ALL: &[&str] = &[")?;
    for key in &all {
        writeln!(out, "    {key:?},")?;
    }
    writeln!(out, "];")?;
    emit(&root, &[], &mut out)?;

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    fs::write(Path::new(&out_dir).join("keys.rs"), out)?;
    Ok(())
}

/// Walks the JSON into the namespace tree, recording every base key in `all`.
fn collect(
    node: &Value,
    path: &[&str],
    into: &mut Namespace,
    all: &mut Vec<String>,
) -> Result<(), Box<dyn Error>> {
    let Value::Object(entries) = node else {
        return Err(format!("{}: expected an object", path.join(".")).into());
    };
    for (name, child) in entries {
        let mut child_path = path.to_vec();
        child_path.push(name);
        match child {
            Value::String(template) => {
                let (base, form) = split_plural(name);
                let mut key_path = path.to_vec();
                key_path.push(base);
                all.push(key_path.join("."));
                into.leaves
                    .entry(base.to_owned())
                    .or_default()
                    .push((form.unwrap_or("").to_owned(), template.clone()));
            }
            Value::Object(_) => {
                let nested = into.children.entry(name.clone()).or_default();
                collect(child, &child_path, nested, all)?;
            }
            other => {
                let what = other.to_string();
                return Err(format!("{}: {what} is not a string", child_path.join(".")).into());
            }
        }
    }
    Ok(())
}

/// `files_other` → (`files`, `Some("other")`); `files` → (`files`, `None`).
fn split_plural(name: &str) -> (&str, Option<&str>) {
    match name.rsplit_once('_') {
        Some((base, suffix)) if PLURAL_SUFFIXES.contains(&suffix) => (base, Some(suffix)),
        _ => (name, None),
    }
}

/// Writes one namespace as a `pub mod`, recursively.
fn emit(namespace: &Namespace, path: &[&str], out: &mut String) -> Result<(), Box<dyn Error>> {
    let indent = "    ".repeat(path.len());
    for (name, templates) in &namespace.leaves {
        let key = [path, &[name.as_str()]].concat().join(".");
        writeln!(out, "{indent}/// ```text")?;
        for (form, template) in templates {
            let label = if form.is_empty() {
                String::new()
            } else {
                format!("[{form}] ")
            };
            for line in template.lines() {
                writeln!(out, "{indent}/// {label}{line}")?;
            }
        }
        writeln!(out, "{indent}/// ```")?;
        writeln!(
            out,
            "{indent}pub const {}: &str = {key:?};",
            constant_name(name)
        )?;
    }
    for (name, child) in &namespace.children {
        let child_path = [path, &[name.as_str()]].concat();
        let module = module_name(name);
        writeln!(out, "{indent}/// Keys under `{}`.", child_path.join("."))?;
        if path.last() == Some(&name.as_str()) {
            writeln!(
                out,
                "{indent}// The bundle nests `{name}` under `{name}`; the tree follows the data."
            )?;
            writeln!(out, "{indent}#[allow(clippy::module_inception)]")?;
        }
        writeln!(out, "{indent}pub mod {module} {{")?;
        emit(child, &child_path, out)?;
        writeln!(out, "{indent}}}")?;
    }
    Ok(())
}

/// `workspaceId` → `WORKSPACE_ID`; `no-color` → `NO_COLOR`; `404` → `KEY_404`.
fn constant_name(segment: &str) -> String {
    let snake = snake_case(segment).to_uppercase();
    match snake.chars().next() {
        Some(first) if first.is_ascii_digit() => format!("KEY_{snake}"),
        _ => snake,
    }
}

/// `hintMenu` → `hint_menu`, with a raw identifier when the result is a keyword.
fn module_name(segment: &str) -> String {
    let snake = snake_case(segment);
    if matches!(snake.chars().next(), Some(first) if first.is_ascii_digit()) {
        return format!("key_{snake}");
    }
    if is_keyword(&snake) {
        format!("r#{snake}")
    } else {
        snake
    }
}

/// Camel and kebab case to snake case, ASCII only — the bundle's keys are.
fn snake_case(segment: &str) -> String {
    let chars: Vec<char> = segment.chars().collect();
    let mut out = String::with_capacity(segment.len() + 4);
    for (index, &ch) in chars.iter().enumerate() {
        if ch == '-' || ch == '.' {
            out.push('_');
            continue;
        }
        if ch.is_ascii_uppercase() {
            let previous = index.checked_sub(1).map(|i| chars[i]);
            let next = chars.get(index + 1);
            // `workspaceId` and `v2Beta` break before the capital; `HTTPServer`
            // breaks before the last capital of a run, not inside it.
            let after_lower =
                previous.is_some_and(|p| p.is_ascii_lowercase() || p.is_ascii_digit());
            let before_lower = previous.is_some_and(|p| p.is_ascii_uppercase())
                && next.is_some_and(char::is_ascii_lowercase);
            if after_lower || before_lower {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            continue;
        }
        out.push(ch);
    }
    out
}

/// Strict and reserved keywords that can be raw identifiers. `self`, `super`,
/// `crate` and `Self` cannot, and a bundle key by those names would be
/// a bundle worth renaming rather than generating around.
fn is_keyword(name: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do",
        "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in",
        "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
        "return", "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe",
        "unsized", "use", "virtual", "where", "while", "yield",
    ];
    KEYWORDS.contains(&name)
}
