//! The translation layer, mirrored from `packages/i18n`.
//!
//! The JSON bundles under `packages/i18n/locales` stay where the web build reads
//! them; this crate embeds the CLI bundle at build time and implements the
//! i18next subset it uses: `{{var}}` interpolation, `_one`/`_other` plurals, and
//! locale negotiation. Keys are generated constants, so a misspelled key is a
//! compile error, which is the `ResourceKeys<T>` guarantee restated.
//!
//! Beside the lookup sit the two things every surface needs and no surface
//! should decide alone: which locale to speak ([`locale`]) and how a number, an
//! interval or a wall-clock time reads ([`format`], [`zoned_time`]).
#![forbid(unsafe_code)]

pub mod bundle;
pub mod format;
pub mod locale;
pub mod translator;
pub mod zoned_time;

/// Every key in the CLI bundle, as a constant under a module per namespace.
///
/// `keys::chat::NO_MODEL` is `"chat.noModel"`. Plural forms share one constant:
/// `keys::slash::notes::MEMORY_COUNT` names both `memoryCount_one` and
/// `memoryCount_other`, and the translator picks the form from `count`.
/// Generated by `build.rs` from the same file the translator embeds.
pub mod keys {
    include!(concat!(env!("OUT_DIR"), "/keys.rs"));
}

pub use bundle::{Bundle, BundleError, CLI_NAMESPACE, cli_bundle};
pub use format::{
    DurationParts, DurationUnit, PluralCategory, RelativeSpan, SpanUnit, duration_parts,
    format_number, plural_category, relative_span,
};
pub use locale::{
    DEFAULT_LOCALE, Locale, SUPPORTED_LOCALES, cli_locale_candidates, is_rtl, match_locale,
    normalise_locale, resolve_cli_locale, resolve_first_locale, resolve_locale,
};
pub use translator::{Args, MissingKey, Translator, Value};
pub use zoned_time::{instant_from_zoned_input, is_valid_time_zone, zoned_input_value};
