//! Memory: what an agent has learned about a workspace, kept in `memory/`.
//!
//! **One file per fact**, named by a slug, with frontmatter saying what it is
//! about, and one generated `MEMORY.md` indexing them:
//!
//! ```text
//! <workspace>/memory/
//! ├── MEMORY.md
//! ├── run-full-ci-gate.md
//! └── ui-stack-preferences.md
//! ```
//!
//! ```markdown
//! ---
//! name: ui-stack-preferences
//! description: no shadcn/ui; Tailwind in rem, not px
//! metadata:
//!   type: user
//! ---
//!
//! The user wants an explicit design token layer. See [[design-token-gates]].
//! ```
//!
//! This module is the disk half and nothing else: bytes to [`Memory`] and back.
//! What reaches the prompt, and at what budget, is the agent's memory
//! contributor.
//!
//! A file per fact gives each one a name to be corrected under, a description
//! to be found by, and a body that costs nothing until something opens it. One
//! accumulating file is what a *summary* wants and the wrong shape for a
//! *store*: it re-sends everything ever learned on every request, and the only
//! lever is a token cap cutting the oldest lines off the front.
//!
//! ## Four decisions worth stating
//!
//! **The directory is the truth; `MEMORY.md` is derived.** It is regenerated on
//! every save and never read back: the prompt index comes from
//! [`read_memories`], so a memory deleted by hand leaves the prompt on the next
//! turn whatever the index file still says. It exists because a folder a person
//! opens should describe itself, and being derived is what makes it unable to
//! be wrong in a way that matters.
//!
//! **The slug is the identity**, so saving under a name that exists *replaces*
//! that memory — the whole of how a wrong one is corrected rather than
//! contradicted by a second one beside it.
//!
//! **Reading never fails.** A memory file is workspace content, which means it
//! is whatever a person or a previous turn left there. A malformed one costs
//! that memory, not every turn on the workspace, the same position the skill
//! loader takes on a broken skill.
//!
//! **Every write is atomic.** A temp file beside the target, then a rename, so
//! a crash midway cannot leave half a memory for the next turn to index.
//!
//! It lives in the workspace, inside the jail, so `write_file` and `exec` can
//! both edit it. The `memory` tool is therefore the *intended* way to write
//! these files, not an enforced one.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, LazyLock};

use ghostai_protocol::json::js_trim;
use parking_lot::Mutex;
use regex::Regex;

use crate::errors::{ErrorKind, GhostError, Result};
use crate::frontmatter::parse_frontmatter;

/// The folder inside the workspace that holds them.
pub const MEMORY_DIRNAME: &str = "memory";

/// The generated index inside it. Never read back; see the module docs.
const MEMORY_INDEX_FILENAME: &str = "MEMORY.md";

/// The most of one memory that is read at all.
///
/// A different job from [`MAX_MEMORIES`], and the two are not interchangeable:
/// this one stops a runaway *file* from reaching memory, and that one bounds
/// how many index lines a model is shown.
///
/// The same figure as the skill cap, and the argument transfers: this is what a
/// `read_file` on one of these costs when the model opens it. Nothing here
/// reaches the prompt on its own, and one fact does not need more than twelve
/// kilobytes.
pub const MEMORY_MAX_BYTES: usize = 12 * 1024;

/// The most memories one workspace advertises.
///
/// A bound rather than a courtesy: the index costs a line per memory on every
/// request, and a folder that has accumulated a thousand should meet a wall and
/// a log line rather than a prompt nobody budgeted for.
pub const MAX_MEMORIES: usize = 200;

/// How much of a description an index line carries, in UTF-16 code units.
pub const MAX_MEMORY_DESCRIPTION_CHARS: usize = 200;

/// How `MEMORY.md` says it was generated.
///
/// An HTML comment, so a markdown reader hides it, and the first line, so
/// recognising one costs a prefix check. It exists for a single case that is
/// otherwise silent data loss: on a **case-insensitive filesystem** (macOS,
/// Windows) the `memory/memory.md` an install from before this format left
/// behind *is* the path `MEMORY.md` resolves to, so the first save would
/// replace an operator's notes with a generated list. [`save_memory`] refuses
/// to write over a file that does not carry this line and moves it aside
/// instead.
const INDEX_MARKER: &str = "<!-- generated by ghostai — edit the memories, not this -->";

/// The longest slug a memory may be named. Comfortably a phrase.
pub const MAX_MEMORY_NAME_CHARS: usize = 64;

/// What a memory is *about*, as four kinds.
///
/// Not a free-text tag, and it does two jobs. Writing one forces a model to
/// decide what kind of thing it has learned: a note that is none of the four is
/// usually one that belongs in the conversation rather than on disk. Reading
/// one back tells it how much weight the note carries: a stated preference and
/// a pointer to a document are not the same claim, and the index says which is
/// which so that deciding what to open is not purely a guess from the
/// description.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MemoryType {
    /// Who the user is: role, expertise, standing preferences.
    User,
    /// How they have asked to be worked with, and why.
    Feedback,
    /// An ongoing goal or constraint not derivable from the code.
    Project,
    /// A pointer to something outside the workspace: a URL, a ticket.
    Reference,
}

/// Every kind, in the order the tool's schema lists them.
pub const MEMORY_TYPES: [MemoryType; 4] = [
    MemoryType::User,
    MemoryType::Feedback,
    MemoryType::Project,
    MemoryType::Reference,
];

impl MemoryType {
    /// The spelling in the frontmatter.
    pub fn as_str(self) -> &'static str {
        match self {
            MemoryType::User => "user",
            MemoryType::Feedback => "feedback",
            MemoryType::Project => "project",
            MemoryType::Reference => "reference",
        }
    }

    /// Parses the frontmatter spelling.
    pub fn parse(value: &str) -> Option<MemoryType> {
        MEMORY_TYPES.into_iter().find(|kind| kind.as_str() == value)
    }
}

impl std::fmt::Display for MemoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One fact, as it is on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Memory {
    /// The slug: the filename without `.md`, and what a `[[link]]` names.
    pub name: String,
    /// One line, collapsed and bounded. The basis on which a model opens it.
    pub description: String,
    /// What kind of fact this is.
    pub memory_type: MemoryType,
    /// Everything after the frontmatter, already bounded by [`MEMORY_MAX_BYTES`].
    pub body: String,
    /// Workspace-relative, as the model would pass it to `read_file`.
    pub path: String,
}

/// A memory to save. The path is derived, so it is not asked for.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryInput {
    /// The name asked for; slugged before it becomes a filename.
    pub name: String,
    /// One line, collapsed on write.
    pub description: String,
    /// What kind of fact this is.
    pub memory_type: MemoryType,
    /// The body.
    pub body: String,
}

/// What [`save_memory`] did, so a caller can say which.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SaveMemoryResult {
    /// The slug actually used, which may differ from the one asked for.
    pub name: String,
    /// Workspace-relative, POSIX.
    pub path: String,
    /// True when a memory of that name already existed and was replaced.
    pub replaced: bool,
    /// How many memories the folder holds afterwards.
    pub total: usize,
}

static NOT_SLUG: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new("[^a-z0-9]+").unwrap_or_else(|_| unreachable!("the pattern is a literal"))
});

static WHITESPACE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"\s+").unwrap_or_else(|_| unreachable!("the pattern is a literal"))
});

/// A model-chosen name as a safe file stem, or `None` when nothing survives.
///
/// **This is where the guarantee the `memory` tool gets for free is restored.**
/// That tool's justification over `write_file` is that it takes *no path*:
/// nothing for a model to get wrong and nothing for the jail to adjudicate. A
/// named memory puts a model-chosen string back into a filename, so the
/// guarantee has to be re-established somewhere, and it is
/// here rather than in the tool's schema: the result is `[a-z0-9-]` and nothing
/// else, so it cannot contain `/`, `\`, `.` or `..` and cannot leave `memory/`
/// by construction rather than by a check somebody could forget to call.
///
/// It **slugs rather than rejects**: `UI Stack Preferences` becomes
/// `ui-stack-preferences`, which is the useful answer. Refusing would cost a
/// round trip to teach a rule that could simply have been applied, and callers
/// report the name that was actually used, so nothing is silently renamed.
///
/// `MEMORY.md`'s stem is refused outright, because the index is generated: a
/// memory named `memory` would be replaced by the next save with no error
/// anyone could see.
pub fn memory_slug(raw: &str) -> Option<String> {
    let lowered = js_trim(raw).to_lowercase();
    let dashed = NOT_SLUG.replace_all(&lowered, "-");
    let trimmed = dashed.trim_matches('-');
    // The slug is ASCII by now, so a byte cap is the code-unit cap. The cap
    // can land on a separator, and a stem ending in one is untidy in a
    // directory listing for no reason.
    let capped = &trimmed[..trimmed.len().min(MAX_MEMORY_NAME_CHARS)];
    let slug = capped.trim_end_matches('-');

    if slug.is_empty() || is_index_stem(slug) {
        return None;
    }
    Some(slug.to_owned())
}

/// One lock per workspace, so writers queue rather than interleave.
///
/// **Process-wide, not per-instance, and that is the point.** A save is a
/// read-modify-write of the *folder*: the memory itself, then the index
/// regenerated from everything in it, so two saves landing together would each
/// write an index that does not know about the other's file. A lock owned by an
/// instance would not be seen by a second one.
///
/// In-process is enough: one process owns an install. Entries are dropped when
/// their last holder lets go, so this does not grow an entry per workspace
/// forever.
static LOCKS: LazyLock<Mutex<HashMap<PathBuf, Arc<Mutex<()>>>>> =
    LazyLock::new(|| Mutex::new(HashMap::new()));

fn with_memory_lock<T>(workspace_root: &Path, work: impl FnOnce() -> T) -> T {
    let lock = LOCKS
        .lock()
        .entry(workspace_root.to_path_buf())
        .or_default()
        .clone();
    let result = {
        let _held = lock.lock();
        work()
    };
    // Identity, not presence: if someone queued behind us they hold a clone,
    // and the entry stays for them.
    let mut locks = LOCKS.lock();
    if locks
        .get(workspace_root)
        .is_some_and(|entry| Arc::ptr_eq(entry, &lock) && Arc::strong_count(entry) == 2)
    {
        locks.remove(workspace_root);
    }
    result
}

/// Every loadable memory in a workspace, sorted by name.
///
/// Sorted because the result lands in the provider's cached prefix, and a
/// directory order that varies between hosts would move that prefix for no
/// reason anyone could see. The sort key is UTF-16 code units, the order the
/// web client and the stored index agree on.
///
/// A workspace with no `memory/` folder is the empty list. That is the ordinary
/// case rather than a misconfiguration, so it is not logged.
pub fn read_memories(workspace_root: &Path) -> Vec<Memory> {
    let dir = workspace_root.join(MEMORY_DIRNAME);

    let Ok(entries) = fs::read_dir(&dir) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .filter_map(std::result::Result::ok)
        .filter(|entry| entry.file_type().is_ok_and(|kind| kind.is_file()))
        .filter_map(|entry| {
            entry
                .file_name()
                .to_str()
                .and_then(|name| name.strip_suffix(".md"))
                .map(str::to_owned)
        })
        // The index is generated from these, so reading it back as one of them
        // would advertise a memory whose body is a list of the others.
        //
        // Case-insensitively, which also skips the `memory.md` an install from
        // before this format left behind: on a case-insensitive filesystem it
        // *is* `MEMORY.md`, and on a case-sensitive one it is a file with no
        // frontmatter that would otherwise warn on every turn forever.
        .filter(|name| !is_index_stem(name))
        .collect();
    names.sort_by(|a, b| a.encode_utf16().cmp(b.encode_utf16()));

    if names.len() > MAX_MEMORIES {
        tracing::warn!(
            dir = %dir.display(),
            found = names.len(),
            max = MAX_MEMORIES,
            "more memory files than the cap; the rest are not advertised"
        );
        names.truncate(MAX_MEMORIES);
    }

    names
        .iter()
        .filter_map(|name| read_one(&dir, name))
        .collect()
}

/// Creates or replaces one memory, then regenerates the index.
///
/// Both under the lock and in that order. The index is derived from the folder,
/// so it has to be written after the file it describes: the other order
/// publishes a line pointing at something that is not there yet, and a turn
/// landing in between would advertise a memory `read_file` cannot open.
pub fn save_memory(workspace_root: &Path, memory: &MemoryInput) -> Result<SaveMemoryResult> {
    // Slugged here as well as by the caller, and deliberately: this is the
    // function that turns a string into a path, so it is the one that must not
    // be able to be handed a bad one.
    let name = memory_slug(&memory.name).ok_or_else(|| {
        GhostError::new(
            ErrorKind::InvalidInput,
            format!("memory name is not usable as a filename: {}", memory.name),
        )
        .with_detail("name", memory.name.as_str())
    })?;

    let dir = workspace_root.join(MEMORY_DIRNAME);

    with_memory_lock(workspace_root, || {
        let before = read_memories(workspace_root);
        let replaced = before.iter().any(|existing| existing.name == name);

        fs::create_dir_all(&dir)?;
        let rendered = render_memory(&MemoryInput {
            name: name.clone(),
            ..memory.clone()
        });
        write_atomic(&dir.join(format!("{name}.md")), &rendered)?;

        let after = read_memories(workspace_root);
        let index = dir.join(MEMORY_INDEX_FILENAME);
        preserve_ungenerated(&index)?;
        write_atomic(&index, &render_index(&after))?;

        Ok(SaveMemoryResult {
            path: format!("{MEMORY_DIRNAME}/{name}.md"),
            name,
            replaced,
            total: after.len(),
        })
    })
}

/// Moves aside whatever is at the index path and was not written by us.
///
/// The case this exists for is `memory/memory.md` on a case-insensitive
/// filesystem: it resolves to the same file as `MEMORY.md`, so writing the
/// generated index would overwrite an operator's notes from the format this one
/// replaced. Renaming to `.replaced` keeps them on disk under a name that is
/// not a memory, which is the promise the memory documentation makes.
///
/// A read failure is not fatal: a folder that cannot be read cannot be written
/// either, and the write immediately after will say so with a real error.
fn preserve_ungenerated(index: &Path) -> Result<()> {
    let Ok(existing) = fs::read_to_string(index) else {
        return Ok(());
    };
    if existing.starts_with(INDEX_MARKER) {
        return Ok(());
    }
    let mut aside = index.as_os_str().to_owned();
    aside.push(".replaced");
    fs::rename(index, PathBuf::from(aside))?;
    Ok(())
}

/// The bytes of one memory file.
///
/// Writes `metadata.type` nested, because that is the format, and reads back
/// flat, because the frontmatter parser flattens one level. The asymmetry is
/// documented at both ends.
pub fn render_memory(memory: &MemoryInput) -> String {
    [
        "---".to_owned(),
        format!("name: {}", memory.name),
        format!("description: {}", collapse(&memory.description)),
        "metadata:".to_owned(),
        format!("  type: {}", memory.memory_type),
        "---".to_owned(),
        String::new(),
        js_trim(&memory.body).to_owned(),
        String::new(),
    ]
    .join("\n")
}

/// The whole of `MEMORY.md`.
///
/// Relative links, because this file sits *inside* `memory/` and is read by a
/// person with an editor or a browser open on the folder. The prompt's index is
/// rendered separately with full workspace-relative paths, since those strings
/// go straight back to `read_file` and a prefix the model has to reconstruct is
/// one it can reconstruct wrongly.
pub fn render_index(memories: &[Memory]) -> String {
    let mut lines = vec![
        INDEX_MARKER.to_owned(),
        String::new(),
        "# Memory".to_owned(),
        String::new(),
        "One file per fact. Regenerated from this folder on every save — edit the".to_owned(),
        "memories, not this list.".to_owned(),
        String::new(),
    ];
    if memories.is_empty() {
        lines.push("_Nothing recorded yet._".to_owned());
    } else {
        lines.extend(memories.iter().map(|memory| {
            format!(
                "- [{name}]({name}.md) _({kind})_ — {description}",
                name = memory.name,
                kind = memory.memory_type,
                description = memory.description
            )
        }));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn read_one(dir: &Path, name: &str) -> Option<Memory> {
    let file = dir.join(format!("{name}.md"));

    let Ok(text) = fs::read_to_string(&file) else {
        tracing::warn!(memory = name, file = %file.display(), "memory could not be read");
        return None;
    };

    let parsed = parse_frontmatter(truncate_bytes(&text));

    // The description is the entire basis on which a model decides to open the
    // file, so a memory without one cannot be advertised: an index line reading
    // "**ci-gate**: " teaches it that the memory is about nothing.
    let description = collapse(parsed.fields.get("description").map_or("", String::as_str));
    if description.is_empty() {
        tracing::warn!(memory = name, file = %file.display(), "memory has no description; skipped");
        return None;
    }

    // A memory whose kind is missing or misspelled is still a memory, so it is
    // kept and filed under the kind that assumes least. Refusing it would lose
    // a fact over a label, and `project` is what a hand-written note that never
    // heard of the vocabulary actually is.
    let declared = parsed
        .fields
        .get("metadata.type")
        .map_or("", String::as_str);
    let memory_type = MemoryType::parse(declared);
    if !declared.is_empty() && memory_type.is_none() {
        tracing::warn!(
            memory = name,
            file = %file.display(),
            r#type = declared,
            "memory has an unrecognised metadata.type; read as project"
        );
    }

    Some(Memory {
        name: name.to_owned(),
        description: take_units(&description, MAX_MEMORY_DESCRIPTION_CHARS),
        memory_type: memory_type.unwrap_or(MemoryType::Project),
        body: parsed.body,
        path: format!("{MEMORY_DIRNAME}/{name}.md"),
    })
}

/// Writes beside the target and renames over it.
///
/// The temp file is in the same directory deliberately: a rename across
/// filesystems is a copy, and a copy is not atomic.
fn write_atomic(target: &Path, text: &str) -> Result<()> {
    let mut temp = target.as_os_str().to_owned();
    temp.push(".tmp");
    let temp = PathBuf::from(temp);
    fs::write(&temp, text)?;
    fs::rename(&temp, target)?;
    Ok(())
}

/// One line, whatever it arrived as. A description spanning two breaks an index.
fn collapse(text: &str) -> String {
    js_trim(&WHITESPACE.replace_all(text, " ")).to_owned()
}

/// Case-insensitively, because that is how the filesystem may see it.
fn is_index_stem(name: &str) -> bool {
    let stem = MEMORY_INDEX_FILENAME
        .strip_suffix(".md")
        .unwrap_or(MEMORY_INDEX_FILENAME);
    name.to_lowercase() == stem.to_lowercase()
}

/// The first `units` UTF-16 code units of a string.
fn take_units(text: &str, units: usize) -> String {
    if text.encode_utf16().count() <= units {
        return text.to_owned();
    }
    String::from_utf16_lossy(&text.encode_utf16().take(units).collect::<Vec<_>>())
}

/// At most [`MEMORY_MAX_BYTES`] of a file, cut on a character boundary.
fn truncate_bytes(text: &str) -> &str {
    if text.len() <= MEMORY_MAX_BYTES {
        return text;
    }
    // Back up to the start of the character the cap landed inside: the bound
    // holds and a multi-byte character is dropped whole rather than corrupting
    // what follows.
    let mut cut = MEMORY_MAX_BYTES;
    while !text.is_char_boundary(cut) {
        cut -= 1;
    }
    &text[..cut]
}
